run:
  timeout: 3m

linters-settings:
  goconst:
    min-len: 3
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
      - importShadow
      - unnamedResult
      - unnecessaryBlock
    settings:
      rangeValCopy:
        sizeThreshold: 512
      hugeParam:
        sizeThreshold: 512
  gocyclo:
    min-complexity: 16
  lll:
    line-length: 300
  misspell:
    locale: US
  revive:
    min-confidence: 0

issues:
  exclude-rules:
    # Disable linters that are annoying in tests.
    - path: _test\.go
      linters: [gosec]

linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - copyloopvar
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - gochecknoinits
    - goconst
    - gocritic
    - godot
    - gofmt
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nolintlint
    - prealloc
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
